import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is generated from the docs/ folder structure.
 * - Order pages with `sidebar_position` in their front matter.
 * - Name and order folders with a `_category_.json` file inside them.
 * See CONTRIBUTING.md for details.
 */
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
